name: flutter_thaana
description: Thaana utilities for flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.0.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MVTypewriter
      fonts:
        - asset: fonts/MVTypewriter.ttf